image: golang:1.11

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test

before_script:
  - mkdir -p /go/src/github.com/torlenor /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/github.com/torlenor/alolstats
  - ln -s /go/src/github.com/torlenor /go/src/_/builds/torlenor
  - cd /go/src/github.com/torlenor/alolstats
  - make deps

build:
  stage: build
  script:
    - make

unit_tests:
  stage: test
  script:
    - make test
    - go tool cover -func coverage.out
